                    OpenGrADS User Contributed Extensions

The OpenGrADS User Defined Extensions (UDXTs) are a collection of
dynamically linker user defined commends (UDCs) and User Defined
Functions (UDFs) that complements the Grid Analysis and Display System
(GrADS). For building from sources see file BUILD.

REQUIREMENTS

C compiler, preferably gcc
Fortran 90 compiler, preferably gfortran
Cairo graphics library for building gxyat; you may need to tinker with
gxyat?GNUmake

BUILD INSTRUCTIONS

There is nothing to configure here. Just type

% make install

and everything should build (except perhaps for gxyat if you do not
have cairo installed). In stand alone mode, extensions will be
installed under ./bin. When bundled within a grads source tree
extensions will be installed under ../bin.

ADDITIONAL INFORMATION:

 http://opengrads.org/wiki/index.php?title=User_Defined_Extensions
 http://opengrads.org/wiki
 http://grads.iges.org/grads




