#
# GNU makefile for the Poisson solver UDF
# This is an implementation based on dynamically linked UDFs
# available in GrADS at least later than v1.9b4.
#

export PODS=fish.pod
export EXTRAS=fishpak.o ftn_fish.o

%: 
	@$(MAKE) -f ../gex.mk $@ CSRC=fish.c 


