#
# GNU makefile for sample Dynamically Linked UDFs.
#

export PODS=gsudf.pod saakeskus.pod_
export GSFS=dewpt.gsf  epi.gsf  ept.gsf  plcl.gsf  shear.gsf\
            srh1km.gsf srh3km.gsf \
            tlcl.gsf  ttindex.gsf\
            wchill.gsf tsindex.gsf # speed.gsf x_cdiff.gsf


%:
	@$(MAKE) -f ../gex.mk $@

